name: CI

on:
  pull_request:
    branches: [develop, master]

jobs:
  lint:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt --continue

      - name: Report Detekt Results
        if: failure()
        uses: motlin/checkstyle-results@v1
        with:
          checkstyle_files: "**/build/reports/detekt/detekt.xml"

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test --continue

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          fail-on-empty: false
          name: Unit Tests Results
          path: '**/build/test-results/test*/TEST-*.xml'
          reporter: java-junit

  build_apk_aab:
    name: Release APK and AAB
    runs-on: ubuntu-latest
    needs: [lint, test]

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_SIGN_KEY_ALIAS: ${{ secrets.KEYSTORE_SIGN_KEY_ALIAS }}
      KEYSTORE_SIGN_KEY_PASSWORD: ${{ secrets.KEYSTORE_SIGN_KEY_PASSWORD }}
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Checkout keystore repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: keystore

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Build release artifacts
        run: |
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
