name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

permissions:
  checks: write

jobs:
  lint:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt --continue

      - name: Report Detekt Results
        uses: motlin/checkstyle-results@v1
        with:
          checkstyle_files: "**/build/reports/detekt/detekt.xml"

#      - name: Set up reviewdog
#        if: failure()
#        uses: reviewdog/action-setup@v1
#        with:
#          reviewdog_version: latest
#
#      - name: Run reviewdog on all Detekt reports
#        if: failure()
#        run: |
#          find . -type f -path "**/build/reports/detekt/detekt.xml" | while read file; do
#            echo "Reviewdog for $file"
#            reviewdog -f=checkstyle \
#              -name="Detekt report" \
#              -reporter=github-pr-check \
#              -level=warning \
#              < "$file"
#          done
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test --continue

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          fail-on-empty: false
          name: Unit Tests Results
          path: '**/build/test-results/test*/TEST-*.xml'
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
