name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

permissions:
  checks: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

#      - name: Cache Gradle dependencies
#        id: cache-gradle
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: ${{ runner.os }}-gradle-
#
#      - name: Set Gradle permissions
#        run: chmod +x ./gradlew

  lint:
    name: Detekt
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

#      - name: Restore Gradle cache
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt --continue

      - name: Set up reviewdog
        if: failure()
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog on all Detekt reports
        if: failure()
        run: |
          find . -type f -path "**/build/reports/detekt/detekt.xml" | while read file; do
            echo "Reviewdog for $file"
            reviewdog -f=checkstyle \
              -name="Detekt report" \
              -reporter=github-pr-check \
              -level=warning \
              < "$file"
          done
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

#      - name: Restore Gradle cache
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: ${{ runner.os }}-gradle-

      - name: Run Unit Tests
        run: ./gradlew test --continue

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          fail-on-empty: false
          name: Unit Tests
          path: '**/build/test-results/test*/TEST-*.xml'
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
