name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  quality-check:
    name: Build, Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt --continue

      - name: Collect Detekt Reports
        run: |
          mkdir -p detekt-reports

          find . -type f -path "*/build/reports/detekt/detekt.xml" | while read file; do
            module_path=$(dirname "$file" | sed -E 's|^\./(.*)/build/reports/detekt$|\1|')
            module_name=$(echo "$module_path" | tr '/' '-')

            cp "$file" "detekt-reports/${module_name}-detekt.xml"
          done

      - name: Upload Detekt Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-reports
          path: detekt-reports
          if-no-files-found: warn

      - name: Run Unit Tests
        run: ./gradlew test --continue

      - name: Collect Unit Test Reports
        run: |
          mkdir -p unit-test-reports

          find . -type d -path "*/build/test-results/test*/" | while read dir; do
            module_path=$(echo "$dir" | sed -E 's|^\./(.*)/build/test-results/test.*|\1|')
            module_name=$(echo "$module_path" | tr '/' '-')

            cp -r "$dir" "unit-test-reports/${module_name}-test-results"
          done

      - name: Upload Unit Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: unit-test-reports/
          if-no-files-found: warn
