name: Release

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  release:
    name: GitHub Release APK
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/master'

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_SIGN_KEY_ALIAS: ${{ secrets.KEYSTORE_SIGN_KEY_ALIAS }}
      KEYSTORE_SIGN_KEY_PASSWORD: ${{ secrets.KEYSTORE_SIGN_KEY_PASSWORD }}
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Checkout keystore repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: keystore

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Build release APK
        run: |
          ./gradlew assembleRelease --stacktrace

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
